language: java
jdk:
  - oraclejdk9
  - openjdk9

install:
  - wget https://csdms.colorado.edu/pub/tools/gwt/gwt-2.5.1.zip
  - unzip -qq gwt-2.5.1.zip
  - export GWT_HOME=$PWD/gwt-2.5.1
  - export PATH=$PATH:$GWT_HOME

script:
  - ant test.prod
