language: java
jdk:
  - oraclejdk7

cache:
  directories:
    - $HOME/gwt-2.5.1

sudo: false

before_install:
  - bash .travis/install_gwt.sh
  - export GWT_HOME=$HOME/gwt-2.5.1
  - export PATH=$PATH:$GWT_HOME

script:
  - ant test.prod
