language: java
jdk:
  - oraclejdk7

cache:
  directories:
    - $HOME/gwt-2.5.1

sudo: false

before_script:
  - bash .travis/install_gwt.sh
  - export GWT_HOME=$HOME/gwt-2.5.1
  - export PATH=$PATH:$GWT_HOME
  - echo "GWT_HOME = $GWT_HOME"
  - ls -l $GWT_HOME

script:
  - echo "PWD = $PWD"
  - ant test.prod
