language: java
jdk:
  - oraclejdk8
  - openjdk7

sudo: false

before_script:
  - wget http://csdms.colorado.edu/pub/tools/gwt/gwt-2.5.1.zip
  - unzip -qq gwt-2.5.1.zip
  - export GWT_HOME=$PWD/gwt-2.5.1
  - export PATH=$PATH:$GWT_HOME

script:
  - ant test.prod
